---
- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true
  notify:
    - start nginx

- name: Add nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Add default site
  template: src=sites-available/default dest=/etc/nginx/sites-available/default
  notify:
    - restart nginx

- name: Docs web site
  template: src=sites-available/docs dest=/etc/nginx/sites-available/docs
  notify:
    - restart nginx

- name: link to sites-enabled
  file: dest=/etc/nginx/sites-enabled/docs src=/etc/nginx/sites-available/docs state=link
  notify:
    - restart nginx
  when: enable_docs

- name: Add uWSGI params
  copy: src=uwsgi/configs/uwsgi_params dest=/etc/nginx/uwsgi_params
  notify:
    - restart nginx

- name: Add SSL Cert
  copy: src=ssl/certs/localhost.cert dest=/etc/ssl/certs/localhost.cert
  notify:
    - restart nginx

- name: Add SSL Key
  copy: src=ssl/private/localhost.key dest=/etc/ssl/private/localhost.key
  notify:
    - restart nginx

- name: Add SSL DHE Cert
  copy: src=ssl/certs/dhparam.pem dest=/etc/ssl/certs/dhparam.pem
  notify:
    - restart nginx

- name: Install ufw
  apt: name=ufw

- name: Install gettext
  apt: name=gettext

- name: Allow ssh through firewall
  ufw: proto=tcp port=22 rule=allow

- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny

- name: Allow nginx firewall
  ufw: proto=tcp port=80 rule=allow

- name: Allow nginx ssl firewall
  ufw: proto=tcp port=443 rule=allow

- name: install failtoban
  apt: name=fail2ban

- name: add failtoban nginx req limit config
  copy: src=etc/fail2ban/filter.d/nginx-req-limit.conf dest=/etc/fail2ban/filter.d/nginx-req-limit.conf
  notify:
    - restart fail2ban

- name: add failtoban local config
  copy: src=etc/fail2ban/jail.local dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban

