language: python
python:
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt -r requirements/test.txt"
# command to run tests
script: python setup.py test