---
- name: Create git user
  user: name=git comment="Git Server"

- name: install git
  apt: pkg=git state=installed update_cache=true

- name: check for repo
  stat: path=/home/git/mysite.git
  register: repo

- name: Create bare repo
  shell: git init --bare /home/git/mysite.git
  when: repo.stat.exists == False

- name: public key
  authorized_key: user=git key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  # git remote add ci ssh://git@127.0.0.1:2201/~/batman.git
  # git push ci master

- name: verify permissions
  file: path=/home/git/mysite.git owner=git group=git recurse=yes