---
- name: add apt gpg signing key
  apt_key: url=https://bintray.com/user/downloadSubjectPublicKey?username=gocd state=present

- name: add gocd apt repository
  apt_repository: repo='deb http://dl.bintray.com/gocd/gocd-deb/ /' state=present update_cache=yes

- name: install gocd agent
  apt: pkg=go-agent state=present

- name: Start Go Agent
  service: name=go-agent state=started enabled=true

- name: install build requirements
  apt: pkg="{{ item }}" state=installed update_cache=true
  with_items:
    - build-essential
    - python-dev
    - python-pip

- name: install virtualenv
  pip: name=virtualenv

- name: install fabric
  pip: name=fabric

- name: install ansible
  pip: name=ansible

- name: create .ssh directory
  file: path=/var/go/.ssh owner=go group=go state=directory mode=0700

- name: upload private key to ci server for github.com access
  copy: src=~/.ssh/id_rsa dest=/var/go/.ssh/id_rsa.github

- name: update ssh config to use users github private key
  copy: src=var/go/.ssh/config dest=/var/go/.ssh/config

- name: add known hosts for github
  copy: src=var/go/.ssh/known_hosts dest=/var/go/.ssh/known_hosts

- name: update private key permissions
  file: path=/var/go/.ssh/id_rsa.github owner=go group=go mode=0600 state=file

- include: nodejs.yml
- include: mysql.yml
